<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-12T16:27:06 IST" name="Suite" finished-at="2024-05-12T16:28:21 IST" duration-ms="74734">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.errorValidation()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" name="errorValidation" class="com.tests.ErrorValidation"/>
        <method signature="ErrorValidation.test()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" name="test" class="com.tests.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="StandAloneTest.submitOrder(java.util.HashMap)[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" name="submitOrder" class="com.tests.StandAloneTest"/>
        <method signature="StandAloneTest.orderHistoryTest()[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" name="orderHistoryTest" class="com.tests.StandAloneTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-05-12T16:27:06 IST" name="ErrorValidation" finished-at="2024-05-12T16:28:21 IST" duration-ms="74734">
      <class name="com.tests.ErrorValidation">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" started-at="2024-05-12T16:27:06 IST" name="launchApp" finished-at="2024-05-12T16:27:40 IST" duration-ms="34118" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method retried="true" signature="errorValidation()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" started-at="2024-05-12T16:27:40 IST" name="errorValidation" finished-at="2024-05-12T16:27:41 IST" duration-ms="815" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [incorrect email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [incorrect email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.tests.ErrorValidation.errorValidation(ErrorValidation.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" started-at="2024-05-12T16:27:41 IST" name="tearDown" finished-at="2024-05-12T16:27:41 IST" duration-ms="432" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" started-at="2024-05-12T16:27:41 IST" name="launchApp" finished-at="2024-05-12T16:28:03 IST" duration-ms="21550" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="errorValidation()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" started-at="2024-05-12T16:28:03 IST" name="errorValidation" finished-at="2024-05-12T16:28:05 IST" duration-ms="1780" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [incorrect email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [incorrect email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.tests.ErrorValidation.errorValidation(ErrorValidation.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" started-at="2024-05-12T16:28:06 IST" name="tearDown" finished-at="2024-05-12T16:28:06 IST" duration-ms="421" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" started-at="2024-05-12T16:28:06 IST" name="launchApp" finished-at="2024-05-12T16:28:16 IST" duration-ms="10230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="test()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" started-at="2024-05-12T16:28:16 IST" name="test" finished-at="2024-05-12T16:28:20 IST" duration-ms="3895" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.ErrorValidation@7e990ed7]" started-at="2024-05-12T16:28:20 IST" name="tearDown" finished-at="2024-05-12T16:28:21 IST" duration-ms="399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.ErrorValidation -->
    </test> <!-- ErrorValidation -->
    <test started-at="2024-05-12T16:27:06 IST" name="SubmitOrder" finished-at="2024-05-12T16:28:20 IST" duration-ms="74563">
      <class name="com.tests.StandAloneTest">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" started-at="2024-05-12T16:27:07 IST" name="launchApp" finished-at="2024-05-12T16:27:40 IST" duration-ms="33246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" started-at="2024-05-12T16:27:40 IST" name="submitOrder" data-provider="getData" finished-at="2024-05-12T16:27:46 IST" duration-ms="5545" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@123, product=ZARA COAT 3, email=patiljugal598@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" started-at="2024-05-12T16:27:46 IST" name="tearDown" finished-at="2024-05-12T16:27:46 IST" duration-ms="293" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" started-at="2024-05-12T16:27:46 IST" name="launchApp" finished-at="2024-05-12T16:28:03 IST" duration-ms="17405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" started-at="2024-05-12T16:28:03 IST" name="submitOrder" data-provider="getData" finished-at="2024-05-12T16:28:08 IST" duration-ms="4348" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@123, product=ADIDAS ORIGINAL, email=test_automation@test.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" started-at="2024-05-12T16:28:08 IST" name="tearDown" finished-at="2024-05-12T16:28:08 IST" duration-ms="725" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" started-at="2024-05-12T16:28:08 IST" name="launchApp" finished-at="2024-05-12T16:28:18 IST" duration-ms="10040" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="orderHistoryTest()[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" started-at="2024-05-12T16:28:18 IST" name="orderHistoryTest" finished-at="2024-05-12T16:28:20 IST" depends-on-methods="com.tests.StandAloneTest.submitOrder" duration-ms="1247" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.tests.StandAloneTest.orderHistoryTest(StandAloneTest.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.StandAloneTest@7ce026d3]" started-at="2024-05-12T16:28:20 IST" name="tearDown" finished-at="2024-05-12T16:28:20 IST" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.StandAloneTest -->
    </test> <!-- SubmitOrder -->
  </suite> <!-- Suite -->
</testng-results>
