<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="2" total="5" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-12T13:27:07 IST" name="Suite" finished-at="2024-05-12T13:27:39 IST" duration-ms="31848">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.errorValidation()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" name="errorValidation" class="com.tests.ErrorValidation"/>
        <method signature="ErrorValidation.test()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" name="test" class="com.tests.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-05-12T13:27:07 IST" name="SubmitOrder" finished-at="2024-05-12T13:27:07 IST" duration-ms="11">
    </test> <!-- SubmitOrder -->
    <test started-at="2024-05-12T13:27:07 IST" name="ErrorValidation" finished-at="2024-05-12T13:27:39 IST" duration-ms="31848">
      <class name="com.tests.ErrorValidation">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" started-at="2024-05-12T13:27:08 IST" name="launchApp" finished-at="2024-05-12T13:27:13 IST" duration-ms="5576" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method retried="true" signature="errorValidation()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" started-at="2024-05-12T13:27:13 IST" name="errorValidation" finished-at="2024-05-12T13:27:14 IST" duration-ms="986" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [incorrect email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [incorrect email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.tests.ErrorValidation.errorValidation(ErrorValidation.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" started-at="2024-05-12T13:27:14 IST" name="tearDown" finished-at="2024-05-12T13:27:14 IST" duration-ms="128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" started-at="2024-05-12T13:27:14 IST" name="launchApp" finished-at="2024-05-12T13:27:19 IST" duration-ms="4597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="errorValidation()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" started-at="2024-05-12T13:27:19 IST" name="errorValidation" finished-at="2024-05-12T13:27:19 IST" duration-ms="380" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [incorrect email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [incorrect email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.tests.ErrorValidation.errorValidation(ErrorValidation.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" started-at="2024-05-12T13:27:20 IST" name="tearDown" finished-at="2024-05-12T13:27:20 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" started-at="2024-05-12T13:27:20 IST" name="launchApp" finished-at="2024-05-12T13:27:36 IST" duration-ms="15859" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="test()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" started-at="2024-05-12T13:27:36 IST" name="test" finished-at="2024-05-12T13:27:39 IST" duration-ms="3630" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.ErrorValidation@5276d6ee]" started-at="2024-05-12T13:27:39 IST" name="tearDown" finished-at="2024-05-12T13:27:39 IST" duration-ms="138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.ErrorValidation -->
    </test> <!-- ErrorValidation -->
  </suite> <!-- Suite -->
</testng-results>
